### PR TITLE
Handle exceptions during connection and wait for connection to complete

### PR DESCRIPTION
**Pull request by andersthorsen**
The HubProxyFactory class has two problems

a) Race condition when connecting takes time, for example if the app is slow to start first time
b) Exceptions inside a task will cause a global TaskUnhandledException event

The proposed solution below will
a) Wait for the connection. An alternative would be to return the Task object and let the caller decide.
b) Re-throw any exceptions from the Task. I'm not a big fan of the AggregateException when it only contains one exception, so I'm un-packing it if only one exception occurred.

### CODE REVIEW

**Comment by AndersMalmgren** [comment]
Hi Anders,  thanks for showing interest in my library.  hm,  the problem with waiting is that this will halt the loading of the application,  that's why I queue the subscriptions and wait async for the onstarted method fires and then send the queued subscriptions,  your method will change that behaviour. But we can't let it crash the application offcourse.  We could introduce some kind of onexception callback that the user can listen to if he want to act on said exception. 

When does the race condition happen?

**Comment by andersthorsen** [comment]
My problem is that the changes are sent to the server via another transport method as a Command, and the users should see it's effect in various views in the application for example as a global sum. 

I agree that another approach could be a solution, but then it should be possible to wait for the connection to occur as a silent failure due to a not completed connection is a bad UI pattern imho. It should be possible to clearly indicate the state, for example disable relevant functionality or display a warning.

In my desktop application I've solved this by having the connections managed by a connection manager that will initiate them asynchronously and only allow the application to log in when they are in place and functioning.

**Comment by andersthorsen** [comment]
It's not urgent to fix as I've simply implemented my own IHubProxyFactory and will continue to do so due to the need for using an alternate signalr path (Corporate environment where we cannot install the MS hotfix to support handlers on non-dot paths for the time beeing)

**Comment by andersthorsen** [comment]
I've changed my proposed solution to using callbacks on connection complete, connection failure or failure of background queued subscriptions.

I've also added unit tests for them and some integration tests to better test them against a real signalr connection.

**Comment by AndersMalmgren** [comment]
Yes, I was thinking of something similar. Let me take some time to look at this, its a huge commit :D

**Comment by AndersMalmgren** [comment]
Hi, I have looked at your code tonight, there was to mich stuff in the commit to pull it like it was. So I did a rebase and took the stuff that I liked. I will have to fix the unit tests too.  

I choose to remove the integration test, I'm pretty syre the SignalR have their own integration tests so it does not feel relevant to test that under the scope of this project.

I refactored the code somewhat, please have a look and let me know if you like it, thanks

**Comment by andersthorsen** [comment]
Hi, Thanks for putting in the callbacks. I your framework as it does a good job at making my desktop application (Caliburn Micro based) receive notifications on open items that otherwise would require me to either use the good old refresh-buttons or build something myself.

As for the integration tests, those are a matter of preference. I like them because they let me play with the external frameworks and ensure that I understand their behavior. I was for example a bit surprised by the fact that SignalR Invoke on HubProxy actually seems to perform a bit of work before returning the task.

**Comment by AndersMalmgren** [comment]
Ok, let me see what I can come up with. I'm closing this request, start a issue ticket if you run into problems or so

**Pull request closed without merging**
